service_name = "manager"
service_env = "local"  # local / prod
http_port = 8081

[database]
host = "localhost"
port = 5432
user = "manager_user"
name = "manager_db"
sslmode = "disable"

[tls]
enabled = false
cert_file = ""
key_file = ""
ca_file = ""
